#!/usr/bin/env bash

# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# A tiling window manager for macOS
# https://github.com/koekeishiya/yabai

# Disable Apple's shitty window manager
#launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &


yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
sudo /opt/homebrew/bin/yabai --load-sa

# global settings
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off
yabai -m config window_origin_display       default
yabai -m config window_placement            second_child
yabai -m config window_shadow               on
yabai -m config window_opacity              off
yabai -m config window_opacity_duration     0.0
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90
yabai -m config insert_feedback_color       0xffd75f5f
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                off
yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap

# general space settings
yabai -m config layout                      bsp
yabai -m config top_padding                 6
yabai -m config bottom_padding              6
yabai -m config left_padding                6
yabai -m config right_padding               6
yabai -m config window_gap                  6

# apps to not manage (ignore)
yabai -m rule --add app="^Réglages Système$" manage=off
yabai -m rule --add app="^System Settings" manage=off
yabai -m rule --add app="^CleanMyMac" manage=off
yabai -m rule --add app="^Finder" manage=off
yabai -m rule --add app="^Webex" manage=off
yabai -m rule --add app="^MAMP" manage=off
yabai -m rule --add app="^League of Legends" manage=off
yabai -m rule --add app="^Riot Client" manage=off
yabai -m rule --add app="^OP.GG" manage=off
yabai -m rule --add app="^UAD Meter & Control Panel" manage=off

echo "yabai configuration loaded.."
